name: jobs control and matrix strategies

on:
  push:
  
jobs:
  concurrency-job1:
    runs-on: ubuntu-latest
    concurrency:
      group: test1
    steps:
      - run: |
          echo "running concurrency job1"
          sleep 10
          
  concurrency-job2:
    runs-on: ubuntu-latest
    concurrency:
      group: test2
    steps:
      - run: |
          echo "running concurrency job2"
          sleep 10    
      
  deploy-job:
    name: deployment job
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: test build output
        run: echo ${{ needs.build-job.outputs.build-output}}
        
  build-job:
    outputs:
      build-output: ${{ steps.buildStep.outputs.buildOut}}
    name: build job
    runs-on: ubuntu-latest
    container:
      image: oven/bun:slim
    steps:
      - name: define output variable
        id: buildStep
        run: |
          bunver=$(bun --version)
          echo "buildOut=$bunver" >> "$GITHUB_OUTPUT"
